config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # create routes for talent index as root
  # create resources for talents with talent services
  root 'home#index'
  resources :talents do
    resources :talent_services
  end

  resources :carts, only: [:show, :destroy]
  resources :cart_items, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  include Purchasable

  belongs_to :bookable, polymorphic: true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy

  accepts_nested_attributes_for :cart_items, allow_destroy: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :purchasable, polymorphic: true
end

app/models/concerns/bookable.rb
module Bookable
  extend ActiveSupport::Concern
  included do 
    # belongs_to :booking, as: :bookable
  end
end

app/models/concerns/purchasable.rb
module Purchasable
  extend ActiveSupport::Concern
  included do 
    # belongs_to :cart_item, as: :purchasable
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart
  belongs_to :payment
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :purchasable, polymorphic: true
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/talent.rb
class Talent < ApplicationRecord
  include Bookable

  belongs_to :user
  has_many :talent_services

  has_many_attached :images
end

app/models/talent_service.rb
class TalentService < ApplicationRecord
  belongs_to :talent
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :registerable

  has_many :talents

  has_many :carts do
    def current
      find_or_create_by(checked_out_at: nil)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_cart
    current_or_guest_user.carts.current
  end

  helper_method :current_cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create
    cart_item = current_cart.cart_items.find_or_initialize_by(cart_item_params)

    if cart_item.save
      respond_to do |format|
        format.html { redirect_to talents_path }
        format.json { render json: { message: 'Item added to cart', cart_item: cart_item, cart_items_count: current_cart.cart_items.count } }
      end
    else
      respond_to do |format|
        format.html { redirect_to talents_path }
        format.json { render json: { message: "Item could not be added to cart. #{cart_items.errors.full_messages.join}" } }
      end
    end
  end

  def destroy
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:purchasable_id, :purchasable_type)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  end

  def destroy
    @cart = current_cart
    @cart.destroy
    redirect_to talents_path, notice: 'Your cart is currently empty'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/talents_controller.rb
class TalentsController < ApplicationController
  def index
    @talents = Talent.all.order("RANDOM()").where.not(id: current_cart.cart_items.where(purchasable_type: 'Talent').pluck(:purchasable_id))
  end

  def show
    @talent = Talent.find(params[:id])
  end

  def new
    @talent = User.first.talents.new
  end

  def create
    @talent = User.first.talents.new(talent_params)
    if @talent.save
      redirect_to @talent
    else
      render 'new'
    end
  end

  def edit
    @talent = Talent.find(params[:id])
  end

  def update
    @talent = Talent.find(params[:id])
    if @talent.update(talent_params)
      redirect_to @talent
    else
      render 'edit'
    end
  end

  def destroy
    @talent = Talent.find(params[:id])
    @talent.destroy
    redirect_to talents_path
  end

  private

  def talent_params
    params.require(:talent).permit(
      :name, :description, :subtitle,
      :instagram_url, :instagram_handle,
      :twitter_url, :twitter_handle,
      images: []
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_url(email, size = 80)
        gravatar_id = Digest::MD5::hexdigest(email).downcase
        "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/talents_helper.rb
module TalentsHelper
end

app/views/cart_items/create.html.erb
<h1>CartItems#create</h1>
<p>Find me in app/views/cart_items/create.html.erb</p>

app/views/cart_items/destroy.html.erb
<h1>CartItems#destroy</h1>
<p>Find me in app/views/cart_items/destroy.html.erb</p>

app/views/carts/show.html.erb
<div class="container">
  <br>
  <div id="list-tab" class="list-group" role="tablist" data-contoller="cart">
    <% current_cart.cart_items.each_with_index do |cart_item, index| %>
      <a href="#" class="list-group-item list-group-item-action" aria-current="true" data-toggle="list" id="cart-item-<%= index %>">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">
            <%= cart_item.purchasable.name %>
          </h5>
          <small>
            <%= time_ago_in_words current_or_guest_user.updated_at %>
          </small>
        </div>
        <p class="mb-1">
        <%= cart_item.purchasable.subtitle %>
        </p>
        <small>Status: Unconfirmed</small>
      </a>
    <% end %>
  </div>
  <br>
  <div class="row">
    <div class="col-12">
      <%= link_to 'Checkout', cart_path(current_cart), class: 'btn btn-success btn-lg col-12 btn-tada', data: { method: :delete, confirm: "Are you sure?" } %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="frontpage text-center">
  <div class="frontpage-wrapper">
    <%= image_tag "front.png", class: "img-fluid" %>
    <h1>
      Find Your <span>Talent</span>
      <br /> With Us
    </h1>
    <p>
      Join us and explore
      <br /> thousands of people
    </p>
    <%= link_to "Continue", talents_path, class: "btn btn-lg btn-success btn-tada col-12", data: { turbolinks: false } %>

    <!-- <button class="btn btn-lg btn-success col-12">Continue</button> -->
  </div>
</div>

app/views/talents/_form.html.erb
<div class="container">
  <%= form_for(@talent, html: { class: "form"}) do |f| %>
    <div class="row">
      <div class="mb-3">
        <%= f.label :name, class: "form-label" %>
        <%= f.text_field :name, class: "form-control"  %>
      </div>
    </div>

    <div class="row">
      <div class="mb-3">
        <%= f.label :subtitle, class: "form-label" %>
        <%= f.text_field :subtitle, class: "form-control"  %>
      </div>
    </div>

    <div class="row">
      <div class="mb-3">
        <%= f.label :description, class: "form-label" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="mb-3">
        <%= f.label :images, class: "form-label" %>
        <%= f.file_field :images, multiple: true, direct_upload: true, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="mb-3">
        <%= f.label :instagram_handle, class: "form-label" %>
        <%= f.text_field :instagram_handle, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="mb-3">
        <%= f.label :instagram_url, class: "form-label" %>
        <%= f.text_field :instagram_url, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="mb-3">
        <%= f.label :twitter_handle, class: "form-label" %>
        <%= f.text_field :twitter_handle, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="mb-3">
        <%= f.label :twitter_url, class: "form-label" %>
        <%= f.text_field :twitter_url, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="mb-3">
        <%= f.submit "Create Talent" , class: "btn btn-block btn-success btn-tada btn-block" %>
      </div>
    </div>
  <% end %>
</div>

app/views/talents/_navbar.html.erb
<!-- list all @talents using swiper js and bootstrap in html.erb -->
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <%= link_to "Tadaa", root_path, class: "navbar-brand" %>
    <%= link_to "List (#{current_cart.cart_items.count})", cart_path(current_cart), id: "cart-button", class: "btn" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link #{'active' if controller_name == 'home' and action_name == 'index'}" %>
          <%= link_to "Add new talent", new_talent_path, class: "nav-link #{'active' if controller_name == 'talents' and action_name == 'new'}" %>
          <%= link_to "List (#{current_cart.cart_items.count})", cart_path(current_cart), id: "cart-button", class: "nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/talents/_talent.html.erb
<div class="card shadow-sm text-white">
  <%= image_tag talent.images.sample, class: "card-img-top profile", alt: "ryan.png" if talent.images.attached? %>
  <div class="card-img-overlay">
    <button class="btn-lg btn col-12 visibility-hidden"></button>
    <h4 class="card-title">
      <%= talent.name %>
    </h4>
    <p class="card-text">
      <%= talent.description.truncate(50) %>
    </p>
  </div>
</div>

app/views/talents/edit.html.erb
<%= render 'talents/form' %>

app/views/talents/index.html.erb
<%= render 'talents/navbar' %>
<div class="talents" data-controller="swiper">
  <div id="swiper" class="swiper swiper-container">
    <div class="swiper-wrapper">
      <% @talents.each_with_index do |talent, index| %>
        <div class="swiper-slide" id="talent-<%= talent.id %>" data-history="talent-<%= talent.id %>">
          <%= link_to talent do %>
            <%= render 'talents/talent', talent: talent %>
          <% end %>
          <button class="btn btn-lg btn-dark col-12 mt-10" data-controller="purchasable" data-purchasable-id-value="<%= talent.id %>" data-purchasable-type-value="Talent" data-action="click->purchasable#click click->swiper#removeSlide" data-purchasable-response-kind-value="json">Shortlist</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/talents/new.html.erb
<%= render 'talents/form' %>

app/views/talents/show.html.erb
<%= render 'talents/navbar' %> 
<div class="container">
  <div class="talent"> 
    <div class="talents" data-controller="swiper">
      <div id="swiper" class="swiper swiper-container">
        <div class="swiper-pagination"></div>
        <div class="swiper-wrapper">
          <% @talent.images.each do |image| %>
            <div class="swiper-slide">
              <%= image_tag image, class: "card-img-top profile" if image.present? %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card-body">
      <h1 class="card-title"><%= @talent.name %></h4>
      <h4 class="card-subtitle mb-2 text-muted"><%= @talent.subtitle %></h2>
      <p class="card-text">
        <%= @talent.description %>
      </p>
      <div class="social">
        <% if @talent.instagram_url and @talent.instagram_handle %>
          <i class="bi-instagram"></i>
          <%= link_to @talent.instagram_handle, @talent.instagram_url %>
        <% end %>
        <% if @talent.twitter_url and @talent.twitter_handle %>
          <i class="bi-twitter"></i>
          <%= link_to @talent.twitter_handle, @talent.twitter_url  %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<button class="btn btn-lg btn-dark col-12 mt-10" data-controller="purchasable" data-purchasable-id-value="<%= @talent.id %>" data-purchasable-type-value="Talent" data-action="click->purchasable#click" data-purchasable-response-kind-value="html" >Shortlist</button>